[project]
name = "python-sdk-examples"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "httpayer==0.2.6",
    "jupyter>=1.1.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]

